version: '3.5'

# This can be used for mocking ansible plays to understand how it interacts with n hosts.
# docker stack deploy ansible_mock --compose-file ansible-mock.yml

services:
  host:
    image: python:2-alpine
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
        max_attempts: 5
      update_config:
        parallelism: 3
      resources:
        limits:
          memory: 64M
    command: tail -f /dev/null
